[theme]
primaryColor = "#1565c0"       # Darker blue for primary elements (buttons, headers)
backgroundColor = "#e3f2fd"    # A slightly darker light blue for the background
secondaryBackgroundColor = "#bbdefb"  # A more saturated secondary background color
textColor = "#0d47a1"          # Dark blue for readability
font = "sans serif"
